artifacts_root: data

llm:
  SEED: 42
  TEMPERATURE: 0.6
  # MODEL_NAME: deepseek-r1:8b
  MODEL_NAME: deepseek-r1:1.5b

# Document upload
documentUpload:
  ALLOWED_FILE_EXTENSIONS: ['.pdf', '.docx', '.txt', '.md']

# Documents preprocessing
preprocessing:
  CHUNK_SIZE: 2048
  CHUNK_OVERLAP: 128
  EMBEDDING_MODEL: BAAI/bge-small-en-v1.5
  RERANKER: ms-marco-MiniLM-L-12-v2
  CONTEXTUALIZE_CHUNKS: True
  N_SEMANTIC_RESULTS: 5
  N_BM25_RESULTS: 5
  N_CONTEXT_RESULTS: 3
  context_prompt: |
    You're an expert in document analysis. Your task is to provide brief, relevant context for a chunk.

    Here is the document:
    <document>
    {document}
    </document>

    Here is the chunk we want to situate within the whole document:
    <chunk>
    {chunk}
    </chunk>

    Provide a concise context (2-3 sentences) for this chunk, considering the following guidelines:
    1. Identify the main topic or concept discussed in the chunk.
    2. Mention any relevant information or comparisons from the broader document context.
    3. If applicable, note how this information relates to the overall theme or purpose of the document.
    4. Include any key figures, dates, or percentages that provide important context.
    5. Do not use phrases like "This chunk discusses" or "This section provides". Instead, directly state the relevant information.

    Please give a short succinct context to situate this chunk within the overall document.
    Context:
  
llm_prompts:
  SYSTEM_PROMPT: |
    You're having a conversation with an user about excerpts of their files. Try to be helpful and answer their questions.
    If you don't know the answer, say that you don't know and try to ask clarifying questions.

  QUERY_TEMPLATE: |
    Here's the information you have about the excerpts of the files:

    <context>
    {context}
    </context>

    One file can have multiple excerpts.

    Please, respond to the query below:

    <question> {question} </question>
    Answer:

  FILE_TEMPLATE: |
    <file>
        <name>{name}</name>
        <content>{content}</content>
    </file>

  vector_store:
    VECTOR_STORE_PATH: data/vector_store
    CONCATENATE_VECTOR_FILE_PATH: data/vector_store/concatenate.db