artifacts_root: data

llm:
  SEED: 42
  TEMPERATURE: 0.6
  N_CONTEXT_RESULTS: 3
  NAME: deepseek-r1:8b

# Document upload
documentUpload:
  ALLOWED_FILE_EXTENSIONS: ['.pdf', '.docx', '.txt', '.md']

# Documents preproceing
preproceing:
  CHUNK_SIZE: 2048
  CHUNK_OVERLAP: 128
  EMBEDDING_MODEL: BAAI/bge-small-en-v1.5
  RERANKER: ms-marco-MiniLM-L-12-v2
  CONTEXTUALIZE_CHUNKS: True
  N_SEMANTIC_RESULTS: 5
  N_BM25_RESULTS: 5